<!DOCTYPE html>
<html>
<head>
    <title>Homer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= $app['request']->getBasePath() ?>/bootstrap/css/bootstrap.min.css">
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
        }

        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }
    </style>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="<?= $app['request']->getBasePath() ?>/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container-narrow">